# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0279af9ba4aca5a1656e7a40858bbfd81c01146006aeec3eaa8e4a8de3f2c443c3c666475e4befe8ba99a63391624720c653679736649b447656f95cae836257

test:
  secret_key_base: 4b2037e0d9c9527f296f3d132783b9880aaf246030ff0260a512ae0c18c62b05f2c202e848f11fc876e369a3a8df0b23219fdf195855788f8405afcd0dd1d1ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
